String orbit() {
  return '''
  <?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
  <gx:Tour>
    <name>Orbit</name>
    <gx:Playlist>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>0</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>10</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>20</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>30</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>40</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>50</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>60</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>70</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>80</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>90</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>100</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>100</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>120</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>130</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>140</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>150</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>160</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>170</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>180</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>190</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>200</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>210</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>220</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>230</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>240</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>250</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>260</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>270</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>280</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>290</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>300</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>310</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>320</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>330</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>340</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>350</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
      <gx:FlyTo>
        <gx:duration>1.2</gx:duration>
        <gx:flyToMode>smooth</gx:flyToMode>
        <LookAt>
            <longitude>76.6084</longitude>
            <latitude>28.8958</latitude>
            <range>2000</range>
            <tilt>70</tilt>
            <heading>360</heading>
            <gx:altitudeMode>relativeToGround</gx:altitudeMode>
        </LookAt>
      </gx:FlyTo>
    </gx:Playlist>
  </gx:Tour>
</kml>
  ''';
}

String balloon() {
  return '''
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
 <name>Task2</name>
 <Style id="weather_style">
   <BalloonStyle>
     <textColor>ffffffff</textColor>
     <text>
        <h1>Sidharth Mudgil</h1>
        <h2>Rohtak, Haryana</h2>
     </text>
     <bgColor>ff15151a</bgColor>
   </BalloonStyle>
 </Style>
 <Placemark id="ww">
   <description>
   </description>
   <LookAt>
     <longitude>76.6084</longitude>
     <latitude>28.8958</latitude>
     <heading>0</heading>
     <tilt>70</tilt>
     <range>4000000</range>
   </LookAt>
   <styleUrl>#weather_style</styleUrl>
   <gx:balloonVisibility>1</gx:balloonVisibility>
   <Point>
     <coordinates>76.6084,28.8958,0</coordinates>
   </Point>
 </Placemark>
</Document>
</kml>
''';
}